language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - "$(npm root -g)"

branches:
  only:
  - master
  - stage
  - test
  - dev
  - unit-testing

env:
  global:
  - secure: "jDg3XClI81GHT0otYUkDc89H1YtRcMDDiDDmmHG8mu97gN7XGCtOs3Neo3zkK7cqqxeY1JU/DcRNamYJnuty22o58XDsQx7SNAGetpg3QYl7TH5cE6YoV4nGRc4ss83XraX5YutsAqWOS7MP+FU1XfzZ1Wa4OKMeWQZAi1TYOtQhfRICuwu6arVwByTdxcG2Y8CdUwmkhIHNBH9k2qmWSnfsJzA73N2AQI2dXaF0pDV941oA9ZkRTgQuqV+5h+NwEhsuWfTHBh8KphmHVEFqJ8UOOthJALCmXVFI4Ut8pCJZbT1DcYZoOsp3F3CJegBTGretCucuu/qJUz6w+AtDSTlLCSVWoh/Lp0CqjC61LH82R2f6E2R6sgtJxH+qfEDWOam2Hju9z5BgZXODzwy5wr8XhLaG75s9VC4YyaxH2OfzRzhgwRwGdqlAwi7BMTzUI255Ox/u5IFfm5JSnuJsWQld0jWJ/IAjV8GnCmIBRI03IG665y99rJrgq8QjRJiNIV7vBENdnbdlUb8gYSYcdCZ9gsKHNPP2t96IUvBOxVwYu0FQ4BFZ+GowKAK7K0xdvKV8k8Yee/1YRZHNiIsRt6N+2aY5otoRM2cWW9PIzF9oYYnO6KVP4edTwf0NIg3vTSJE7QJB1qZoeeUW4O1L3xowj0bRTQhKl/F8ZBuZFY8="

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .

after_success:
- npm run coverage