language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - "$(npm root -g)"

branches:
  only:
  - master
  - stage
  - test
  - dev
  - unit-testing

env:
  global:
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: "jDg3XClI81GHT0otYUkDc89H1YtRcMDDiDDmmHG8mu97gN7XGCtOs3Neo3zkK7cqqxeY1JU/DcRNamYJnuty22o58XDsQx7SNAGetpg3QYl7TH5cE6YoV4nGRc4ss83XraX5YutsAqWOS7MP+FU1XfzZ1Wa4OKMeWQZAi1TYOtQhfRICuwu6arVwByTdxcG2Y8CdUwmkhIHNBH9k2qmWSnfsJzA73N2AQI2dXaF0pDV941oA9ZkRTgQuqV+5h+NwEhsuWfTHBh8KphmHVEFqJ8UOOthJALCmXVFI4Ut8pCJZbT1DcYZoOsp3F3CJegBTGretCucuu/qJUz6w+AtDSTlLCSVWoh/Lp0CqjC61LH82R2f6E2R6sgtJxH+qfEDWOam2Hju9z5BgZXODzwy5wr8XhLaG75s9VC4YyaxH2OfzRzhgwRwGdqlAwi7BMTzUI255Ox/u5IFfm5JSnuJsWQld0jWJ/IAjV8GnCmIBRI03IG665y99rJrgq8QjRJiNIV7vBENdnbdlUb8gYSYcdCZ9gsKHNPP2t96IUvBOxVwYu0FQ4BFZ+GowKAK7K0xdvKV8k8Yee/1YRZHNiIsRt6N+2aY5otoRM2cWW9PIzF9oYYnO6KVP4edTwf0NIg3vTSJE7QJB1qZoeeUW4O1L3xowj0bRTQhKl/F8ZBuZFY8="
  #CODACY_PROJECT_TOKEN=[secured]
  secure: "eHVyIGF4Cwf1yModAY/vs7UY1cBuZIZjMLlpCI0NTR0+svRun7NYCP2iEoGEhVTj2FXbq9OoXwNbowV84Y/1ycrpcXHYZm720invf6Mu/nSBH9xkGf0TZXFI1vbWJCBJWg1PTBgj7hke1hnRsp5kj4eahKLs5JHhDrOdQtAx9vEtvcLMuFxgWuLRtdl99DBC3mnSdd5dwORLqMwK0aqfkQ31xehIppJMDaA4L4VAm5oK2TbqPk7PRBq/KN1VLnAHYbHCv5BGpxHOC4dS91wMv3790MZ3cPkNrArpnSWn9zUOW0jFPPdtTqmEBgtpb61cy1xP5F8AQeRRhNSg9Y+uDW8bDrXlnZSZXA0c5Xzw+1GzUP4efKN9n+IoJGZgdA+gkTlCxSSQXlAk++541LFSMJ6uEzDL1QBx1+ILoejjRB1YsMsqC8DYm4PR3H7yESmc+9WDH1+OUAi3/3SZO7fdzZcO30PpdyqP/0WIN31RLVXbC6+/eL/3owEr1EvbzF+d6tLabjnwKLb1BtdHm2wVbAkcwXdaRpc0nrO0Qt2UGdEKbxk7450D206e+0gyMqNs+U/q82BTpwce+FA5nFV4Y10sIa0odrh0Wm5b7uUWSHEB3VSyIyWM67oe5amxFVOpHZ8oPxKOTTnFyOMhC1ZJU6+TdyeXRWrRh4V3F0h0TJ0="

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .

after_success:
- npm run coverage