language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - $(npm root -g)

branches:
  only:
  - master
  - dev
  - test
  - stage
  - unit-testing

env:
  global:
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: Wt8Fb3bnT2NR1vT2Q0FsTu9y94O9K9uys6ayCvl8J/YiLkKjYSK4ovaXOoHzxyXqVjjmoj8G9vS8GcahNU7SdD2vBS6r9/9I/Vm16lO/vjuW7eGnEmmEheZxLPgU1XgkcuFfejqtToNlTGyEpSQlcFqUk4sKAseHCrePKdu3rQGuKN7rM/GaTWBLVEvF0DQmOIKOd5n644grNB/VVBwwMB0iJR0GbmFIP/KJSTeajDfwFUEZFDqyvtzCSonANxDCeXesXFAihuJJ2uzfTGd6X0Fw5fmjP6qeMV0qCvs3opgqyoR8l5HPhcyQtLonk7h8B1gANRzw5PVIqLhYJWn/oAbh77NxWOUTlmHJ4xxj9vFL0hQcONVJd/XSbivLmtiCXMb5n3tjA25YCATpOSZmhRR26wpkaiWZC4TLp6MWMRwpi3mBv5RUudsL1ZJLgTMjy/QVa2+Tg/Lyfkmie3zYUNWLXuI6/LWrNdERByR4KhaSE5thF2UjwV+KhrDUCkOVQuLWO4zJb653qRxTKqRUASCRR++YzSWA7cr9ICDW8helAHH2YfmEjpFqC7D4Wv4ehmkeEjD1IwIMd+a9Q9sVwJzVjRA8njHgEtBfqsyoVbK/CBEbPDhZjzJ6yiuOzAQ5Mlp5M3M9jCO95bfr6cwYIAHG77Lf/9xZk1Ap0O2ZCz8=
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: d7/okXgEb7ylEHwvc9dqQMsVLzKp3Fp3JQHFNqyDM0TYsDbJ5ZN+wl1+S09POx/DcLhincWzOJ98QusIu+JB6/p8ryrU5qhpNM2afYSt1EGsJy8G5ITXt4GDmLUV+X+gdorDp/0FgQAHXKUI/AiIADGRq1MKs8MDe3d9FcHhxlEHeR6wQODuZGSioev7AaQ9bHek+wcL3L36bL+rTysAH3v5Lpt8eWLEPLtiDVxOQRYd8WApD+rzkndvNZ8A6o1FvNS/QUvv5qqxDzbPv7ZD1Tsf/PANdmMhutQaC8IGyFiXvzzuiC4KsL3d/9Mfm0EGBO718p7UszZQrK21mik8a1dClQaqhrqmvTLIKG43zveLEFe+vmfQI4ScM7GNw9yuO9TsODM8CUK4oasDN340/ZJPxm5M5QB4MW6ZBNAJ+gFyUAskltsvv4XbI92MTlmNBqLfE3m50Uu48nrTip7IF9Qyh0fIh3M01z6e8EiqloRmjhGcgyixJI41Fa73KCcVokTVtAu+3g4kBWYUlulUK2hAb71IvQcQsNg8JfnHVaMqNg/WBRcDJB+X65Z88A4UiQcMgp1wG2V8EH5X4vTrFwnnzcLGQPGSJfxtZUb7hRewGRxguLMU7aO36UfSlTHpWWLUyAZVelLw37WwDsL1NLGcLJedf58AYB4vw5lZqbk=
  #COVERALLS_SERVICE_NAME=[secured]
  - secure: iP80e3b0DaQzv2u5X//OLeB5yZfUkMxQx5mbapu46ZE7GGRieJTe6TLEeQltuaxAjYiE+w5w+jBJ9l6P48LOeojEEyZth13KrOiTfGjTkMHiL9xPaTPgITEyHUNXrBc4PcIA1a05g2FLUAprplWPo+9i4EKNV1o8yzabGEQq2RiKXw4+bLv3+2Bv53/WuaxWaouVDb+Q0qeB+eRcK6IAtujNIZ6QWZld+gO4RBjpd14bnyYq4Cdb6aDQZoSmmjEtCzZkj5mSnIVL8aQEoU9J9EQdj7oW7CSxpw0biJYeD6utG8oksOjYNgDOsy+1NNMYKf9ig46HVjYKOipau+2BwNNcJ6WrfGLWjPpqkPBbGqohPkcCXOUFoWUClyTpKfWz97rJje0ojiVbdNiDWxVzIUEbUM8o+mUuihfQ/mllRW4vQGfaiZjmdbzvXMkLJbe8rFT0C4jZ1Sdo44jb21l+sQfp8jPORSQxoiBlqgTmpl3dcKkKd9tGqAt4iGFDcmMsX+z8Y73onjqEWi9PnPr56uR8hEk8oeuJZtL492576W430/MCxyFhtdHcaV2zKOAVBpR8RKttJH19pi0HE3FDeyItr+FPtERmXtITTS8BIZamD/Rbyk1Rr1Ip/RvKv2EPLUFG00Ck/ZrHjtjbtJgJxdRP+fd2wtBrJPjk5UvFjLI=
  #COVERALLS_REPO_TOKEN=[secured]
  - secure: rqHnBujIc4uyccAlv4mFkD3Jt600B+KO3FZ2JxYLPt18hJ1KBGRxfHA+FQ+GjKYIY5uk6gc7QfjUg9F7ujoYuPGVXUi7FgjUdZHvrz8QSzrI++tLOj34bOFEksY5wmFGoyde/kR+tsADdh2lPMghVDYTf44BV9p734K5qjlO9UITOWb9M/pfwSub/CE7m4TNfBuEN1AURjZRAh4GbebZsHmR1fV8G5scxm3a6dzKLw2Gjn9zaOw2LDWz4ZbspVRKU73IrIU2bcLgIqwyoL56U7gNGE/ckDcoqrCrxHPhtqcz2YMwyIHrpvZPs5q8ZJPNGJ+3eIbBh75hzy+nJN8ta1JSi7tWq8tGep7dvIQCMc48FCoC3exJMfqKnSxhaTQQrbP/TWzOivtiC/r88170BNnDLGwF0PT+3RipvGrILMxB84L6odYAF6BcZOjrPD9fOKruFuZahsk/toLh7r4eFXvK2lTWo5ZG9GHd53xEDLC4f5QYjFbmnoJx8vQWBD095+xE6elP23otJF0PeBtqg3T4CP4MbTUyN+DKwYagB3MRu2Ib0b9Vw/KxSDOZ1J7NQEtaC9QyLo0DswYxOyVmcySCAeXcn9rqM/cYpXRaRRojoFNMhpjlZjyJFkEnFI2kdQRwHXQfs5ix2caBMHmlMO07iugLDTjKxvbg6/PBNDE=

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .

after_success:
- npm run coverage