language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - "$(npm root -g)"

branches:
  only:
  - master
  - unit-testing

env:
  global:
   - secure: "q9IMb7av4hiTAugn/ZLrBJCeDBYbOLV/ow0YoymFErqW+JH8m31LzaCXEr2RJT6cL9HghL6SoCyre5qRwVxFQqxuqEvH47qYyXCkS1wMUulGtha6GyPuonqMx9dr2wyFNGbSPPLE8cK/GqFjm9YiuyVg6BxP9+657sM/QCYoi+MeS66JgQ2wCGS/0erKoWC8V2yjQFuCTNS91C7TL+AFPgG9a2AthTyhyA0v0bZBMAxyfnP6vSBUMdB/6wZN89G2wUQEY1ScAcrIIYhZu/GAsRFeK8YVtZ6nuooHlvDazGogM66JihE4j0HBZ9g07S/PBAQpQooGtc9wlYv5VzXmUqLwJYr9TY57IrV4z3QrEQ+aeXEd0uIixca8v3rehakrPtX65+TxwAdsewE2E8OB4hcGuOStByczDQZ5q9Ov8H4ld+MrbgE7J13QFIBCX4ZH/PMZVxVGvmepETITR9U7BrtsCVooYKkgf+KwBHJbeB6huXRTlhtWLNJW4ghqLemFV/vgqdNyWsOC+NaJMSMfkxXZ5WEGK+uz1Ubz1w/IKQa/qYZu8/ghqIANylfPP9NaH9W8YDNnqBAHUqDcQI0/xYGcSwguMgOeevCCU6hTEhaIROLr1sP8cKjVGYnoA5hapTSektuq3EoC36ujsgNE4Z3pqyJdVmMUkuEWx89ETEQ="

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .

after_success:
- npm run coverage
