language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "k2Hgz/AxIM6NZabY6R9ibSlQTyHKaUTeStQDkIPlunyn9SAblBisTX9LB8YcH2GQdXuGYqQiouR/g+NChKWhnHfSUcRl6QQMyc4WRtz67i0EvHeH5TeeVREpnn3SJqgUNReQAwgSIgfn625WDUD9J9dskyAn+Z/nTUfaTmgnIWGWKZ7/suwsgtmNu9phI3NQBJfRFd/GIlPuglZEDrufqRRtrgwUO1CVDXd1AGUYMOF9ot6ykC7VGDHvCjCjK9e8BxxcIR2furJLoMhZwFgQUsmayn9OolhhcoBWI0v/cm3h9TmjvQfQ/PddYipezRh3JQ5hy7hhFfXSQxkOLRNYGFT7DJbG9aru/9xWeUwoWpSSFfTteu3swCtdTOc5UX7nU/eFzWG3MiPrgMINT7CyV94aQjECFiOufRf/jSY9I112wo9ITirgVfqnsrJ7LViIVa8x7/AYbapJBGg+cZ6qocsQibaHF34+isN/lAJxU6JM9rfPHjVAHAR+BKIsfwMHL0YNMhDcJtsdbjdJz6kbRv5V7+IhCvXAE4JIZVNONjnCRSXYnuSjp8o5HCEEz7GD6lioHXLrr5U70jXnV5MuSrDEvJ6Go2npfJna4ISu6F2eU9k8njna5vZTCkB86C0Zzlc7P6MahRcuozcyRT5Y/TciWpSMIGfr5Q5g/6hR22w="
    # SNYK_API_TOKEN=[secure]
    - secure: "YvD8xBDphP3SnV4GbGEe7iwdAz6qhNyr+3Yf6rv0oXmLbaD8zBA1tlcW8eoDFlT21J+lS0QthX9YO1Um0+i741QYnrAHnuLLkor+S6zytI63csRg+wCNOHcy52YF+iMZ1wwCYyEBLzFL1E5Omfvjbi9kZ6JY0l3vZhu5+T4W0pEPOY/+swIbdl77q+kNhXBX7G17UN8JPQqfwvuvKbAIJGnVBwxwcLenn5LazWgU4eFcj+zsDR0nUxJnrtdxOyVRCakVaKFRMwYv2jryWfdteRrSDMyBVTtPl84x3/vmNcU/qnCBtWbYgK+jX7BEWu5hdg8ify/+ZU+C+4Exy3Pdp1CY9ukFBK3qp15ll3GgqE8/WcH2FuI12EO4Thu2xDjO+ljIVA4SqMVNKyiDk1KM7l2+S+ndtEiF5OGAt3ZyYfHfwaC9KGSYGR9WJqFoQb3XmL0k6UMlYl19geeSPATh/ywUkyfvx4CxR3HUXYXhssDPLL6TgBL+XFBwoizfm/Lpi9cokJFoNch9MXg3/bGer7NGXltRofM8EOaJYezSZWjbMdadMKBHui8lVpIEweHZgPN3qpDk+66AAGbkd/hTt/3AvEELceOrNAA0cFFdbZKBp+gu9/4OzAGzzM7ocIkvtFwcLAnvhBd/WqdDJdL2fz+otERNrS/9qpuujYcttr4="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "WZDGWqiis9eXfC4lGXPenKFGglaQRqQGdsok05jUYEg4vRG9da4EoUchUWQqJxwBkbzYWTxp6xSihPDZdXepFxEDIV2hvVglv/IE0F+OM+rwv0S49hpnilaDslILciTB7yWkN9y7kFRQg3NbFiVFw8RKQEDoE5tBnCG/0BzofXoaZ2v0/0InKaqcbWPPANzUdLicf+96+I0ZYu2H/zwucHkeFsc8ks1YPyJGvfrIIx7d3YzLtQVQAfjhnv4wYe+aOqIKT4KFUhUTFhoCJN9iyyh4qdeG74EWQHLs/GeXGCttbudNOb5u4YcE96RyPddDGJJtmAL+fXdEji1qz9tPfRaRJoOvaT7rlo1J12z3bVWMD5g3f8r4xQOi6+ETCDz+gKE/Jdo3Y2WPXYkOd9Pqij343OOD87h28g0S8jKjaY26ZiC/YfvfAp7WP9MddpdpxJHc1KK3hmOGnmkhJ6a2vohR/duioQUoqwm6FKTPH1LIzfGr+enBNEDkDGaxW0GM0YoldtkOM/VYjjFK5y5zHvlb/1l+o1j59VHb/x0D9hOvIzeQyLLN6DiBNqviZ6wk52NePADMezZ5pZNF0yu56kmQio6MvSCNKjohrzZGlPacbBXKJVtKjbN32/V2GdPC2Ri95hNZoGRP/pvJX0cE31+IqZpw0bK0sWdgTkX5oes="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "OhMN3d7x9zsloWRspNok/b3u48I6l5Gu4eT7Sai8XMRK2HiED9DpFTkRINIMaIqbPrB/nRc5hn46KjizW6fPgYaH0TuXyt4My/Oq5eXIoYqCM0e91uymNNWckqcEJWMqjbNNauoHfDkxJOOd9jvv/xd4gTpUM6BZ5y94DzF0NzDgtCqk1h73dj2b17C4S55l8zFI4lJauletlcWlr3gdIT9GO7RgTXeG/e+v0Xnaa+3vDnF9ghpJJSDl6hjsCwWaclEValSk8cpWekrXEHzRyDaB5nphJmNT940ZAa+xUgx/zcjqWX4ANvYNIzbUjkEbs8hVbdTY4ozt98bFlcIjRpEKh/4wfQkSz0j0PXkNDeVdbMFwgfq1+BI9LahDvxU6BL6289QghstWeylOYBxtYQ/UdDeBdaDwru+hHiffyy8P5Zn3c92XFlXo9sfBGnx7BsUIoL9s00Ra360F3S6R0xm7o/6BpKEHixFc2ebej4cU3VKq2zbin1oALl9j/C2QXS9GudFSR7CxAdAcDN34Su6+SJvdGBwmP/2t9Ebz2JeXqD/sYIvYPTvVw4T0VGUnCJE0ZosLfk3SFXekT3KTentcTaowr39imAvyDB/oZT+uJmhCDLd07zGk9r5ghQ4hr1FSvyHXblJ3OwK3Wvn/EeB7atN0WZypH6wam7BBFcw="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "Od5VLZ56XMidh+Du/nVPgHpeSCrHs4tKnvSIpdr9+lCyetp5c2nZo/OZ/0JXjJsbKjaItnqAjJ0CFnTxdySsiKTAQ/dBPSqzH55F6qQgcLlASOw9ORSHxH/WB75rsy23s3XGz4l0YvC/PFkK3Kg2Bf71WFnuVxkG1fLnHdHIDYi0TCJB3rvdREhlhb3cUhyaLpL5VvWLeBZLpiMpX16mu/2xV04a21+gDVhLUCNMYGlqfVzcPtnsRnj2tv4QgapcfuxWwjxpFZG+c5G8S/uQPb3Vs4W46Cr0kygb+UgDCoimn83l1AWEg2ua2NHaB152SPIhvBrLcW44abxbeMO8DoEFWJuFFvm4AOs+LOaJ2nnjPic45cxK7cmdUsXevQRM+SDayvvcYXbX9m/036GpDosVl+i1nefk/OnWA09adGfsqRWQ8Brf1pLfZhRcBdADVjO2SqEXzKyfq9kgz+VvfduJ02sjZBhbZEGUj3gXeO1l+fEprasLRcdniY1N85tU5d8UlxkzfgNTsX/SIjipdYQmsifP4Td2BkldfiTJlmVwFjIlqd9QEwvqnMicoWKNofuTBzf4ZIhSIXIL0bu22VzNe/6QW9jDiqpkU5sz3hpIHB7IDzQ6Nc6+V3kFtZdWr2hex8pvLQDy2p7YO3QB0CnqwqRs/0CPsACDL6bP1pA="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
