language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - DEEP_NO_INTERACTION=1
    - E2E_TESTING=none
    - secure: 
        Wt8Fb3bnT2NR1vT2Q0FsTu9y94O9K9uys6ayCvl8J/YiLkKjYSK4ovaXOoHzxyXqVjjmoj8G9vS8GcahNU7SdD2vBS6r9/9I/Vm16lO/vjuW7eGnEmmEheZxLPgU1XgkcuFfejqtToNlTGyEpSQlcFqUk4sKAseHCrePKdu3rQGuKN7rM/GaTWBLVEvF0DQmOIKOd5n644grNB/VVBwwMB0iJR0GbmFIP/KJSTeajDfwFUEZFDqyvtzCSonANxDCeXesXFAihuJJ2uzfTGd6X0Fw5fmjP6qeMV0qCvs3opgqyoR8l5HPhcyQtLonk7h8B1gANRzw5PVIqLhYJWn/oAbh77NxWOUTlmHJ4xxj9vFL0hQcONVJd/XSbivLmtiCXMb5n3tjA25YCATpOSZmhRR26wpkaiWZC4TLp6MWMRwpi3mBv5RUudsL1ZJLgTMjy/QVa2+Tg/Lyfkmie3zYUNWLXuI6/LWrNdERByR4KhaSE5thF2UjwV+KhrDUCkOVQuLWO4zJb653qRxTKqRUASCRR++YzSWA7cr9ICDW8helAHH2YfmEjpFqC7D4Wv4ehmkeEjD1IwIMd+a9Q9sVwJzVjRA8njHgEtBfqsyoVbK/CBEbPDhZjzJ6yiuOzAQ5Mlp5M3M9jCO95bfr6cwYIAHG77Lf/9xZk1Ap0O2ZCz8=
    - secure: 
        JPDpkgI8/BEII4eoCv8h4YJYGb+YO64EvbCsUpAFB1QYddb/MrFXnEAOQqnFi9GKd3LqtW1CX40waTKyVg7tAbEoenQn2x3BVKgeDwzAytsXQaILmlxfdR/N1oBYpZevTJCkBTwec0KqZzaYwL6XTvBHE3wMERvZIAhzXH8U/cX/GO78oUA4xg5datkBi2/lx0GHAgVI8/5k3OO8UpGN4ZPQXlS/I787fW98Rusrs8uw/ph+UauI3fW+6mSVZwGHbs4E1ijud4S84bGnBv+4iWgMarmpL/oLzX/ArCy9hKA35GVPlotHZ3bPYpi+rar12iySfMGDUcCmkkAf45ZfNXhyNIXD72uIeKt41DXqp1OzI0m4M59NChy5AYzhytX49kma21i/MnLweanwywL6nGVtaq7UVeSPsp8x19Pjo69QWpgND8iKuU+6hCK08tjSA4iv/UuYvmXM3P9yya3Ppa/mU1q1C9K0WXWFSbW8rSqpHnLG76jDTbN5g5uu+TIzB65ylNb6h8izlpKWww8fzrMAIvWMp4GvnT+3/RAIwIb9nsaqefDxEVaUXvUWG8yciiDn1yQKQAN3J694o7PPloU/AAQVdbARZPvQKesodwu/aaaCel647wV4sXl8nOqpbDT66iqwDUiIwj3BAF5GOU3Xs9A+PVS/A7aDrt8Mk/E=
notifications:
  slack:
    secure: 
      nHDk/C3hKt6IyPA8Hi2yqfwwRJw79cCBdfOJpZDHYH8cw7YgU2f/JBToxMuu+SI8OCBfnsghotoUuMm5sHoyJN+AZGuxbDM/N3hcGAUcCWtZ1Is6v/6JHrZB2xze8VkS6U5r0vJkFHH4iQLUD1M6BeZiMNI5rFl5D+ToltqciQ13qjgOPu40DybOo/Kp7WwqbG6ubvQu9QoYEpjxDGKbjH+N1OZ3tHlAim9QZVALuHb/jjHink8KSBp6tvZ7rWK5sLPmNg8dPqB/+owhzU0yZTEVhyghukS3znsH3dGkYxd6MOz2OXJMPG4Wars3g1sh3dG418LLS5N58jdKJvDPf/EtK1cssQxIP6gPoD87PgIhEY4moUsnGCe7ivj3J3BJqekhmFWI13vojXfCQJdB0R6BuNKXedsxyumpcuA+xLGxO7LqR4XWC/xDAXLdxvFUAn3hOw+aXahe8zGxAvER2INOz1VWOMl+6XWVvtjvpEtC5Ezct3vbuOxJ6kZuTK58w4Q9EYpFYnrXBNzdzDSyth2z61BYQ1o+C8fABUNqDDsgO1MqGj1ziqSjg3al1jcbxVC0zYD+v00LISXfyuCPNQMbYpqCSjUAJeG9IYDcrRPjrZZ6BV0QoeQjYf6Wjic4jI0jaikWJotPWYdsPhVebqYnsbPksjor/DlNn9/gan4=
