language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - unit-testing
env:
  global:
    secure: optd0NIMYYeS4MMTiVbxeXI8DsiMIx6r09V0mn/aE794f7E/VM8SwpztOfJuu88WEsM429r3GZ4QAPOvlOr7aIias3vRZ/MeteO+xjThdLevF+VnhYyyL7ZVjqoeVoqvlGg4SzU3ZButWYlmFtFqlW14QrX2vli40lbl37WtXHkfHcecPdSHH+3WgvJ1UG+hydMPdqMbFpUTOxOeQPeHvItE7s+tMsLrGAoqrZamaHklJEPB4yDccTaIcDuwQ/2lBoHYP7ptVLPBibVEubomicWY7BAfwYOJHpimYewbaQKOoXAY42VTthlLZX6xkTIaat9VVw23fFRK4xdTyAV1wnFnGr1O5+KYUeLI+s+eQI8Ch51u4GU7gt3KffFj3cWiRffAWVbSG6lfZizFR5WdVTy8QaK6avYgLjxxoIMnKB3nE5eSDDC6dVjSnnG26VQqelB0WKScXsnbHzRUxAY/EQj0u30Y1jTO+Yg16TJ/DGOYSdNGFD5+y7ML8f2GBbPrrugmvb6+9ZU7SP78a/ISuSnpCTDzWho05iaGYRyq8kLWbb/0BOGbmSL3fM0BsK1hAIji/T067CCnx9i8lbCFfQi+NBezi4DHPmeAWOhyxobLtVkOcK0ahOuOxB/N0uSxiQFo9Qxya+ZRPUzLzc5YYwhpYBZHpC0rDiHEXjxe0Dc=
before_install:
- npm install -g jspm
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .
after_success:
- npm run coverage
