language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - unit-testing
env:
  global:
  - secure: DeeSEieWjXwpPFJt55ZPozWNZ5eTXG9g5+PMEhOkV8SfF/IJ6yoCSRchRgFL2TbHGI/bB5UZNr0P+hBSvNwQT0BZB6hDZMdWiWZiB/FPUV1ZSq/xc3Sis4pnTkFX32eH/AgFBpkafFFLUqdD9CAFykS643MFcAFk/BZkUKu3N92xAmO6fzUataNyCDCkZ6MYqVqPGYPFgAH7qAfZI31LntkwTpU9BSebJZbRznYvLXZtuYT28GlEbdRyijtnCxmLpqEdHgOPSrng84zB2/Ug8SCjIirwMeyozyVBowDJrFqZnOQbOJ4IHm0G/SnTJnqJMtxtK21tZVKCShObs/HIovsI202G+q2DYv0IuttI7NaM6NLQNuqMh3lQh//sBhJ83rejM9A9G3cERt9Tl2Vunj0WjdBeZJOU6ExEmIVxHuXmRhaWHHm8Yn+gpFADsXCvyAo0VgAWqwwQn2M8CwQvZ8sq3xBePP9MWZfYp/78ohDrRQE1lwfv0MMD27lGc+0/Hb0AO/wNHe7kQU7FXbxBU711RwGp9kmoI+U0b9JyYIfE07qVegqc4lquIXLwNAkd41xxJVEPiuWoF+UeUWA4vqMUBY2nDpWIBkYE35Mm4Gu5TWY7/ucKFQg2ncArp39MlMn+XlMo4QEMAk2xGutLMka3afqirsKXzZxWnG0tgZw=
  - secure: efqC/J9jV9zrGSsnOY58PBaeOcCoGVoCoIQ9vKD0cuzDQdkEzBL4oNYbZsZc+3+OZVIO3GJVNHKj1HkqJ+u9H1CjtE812jx+48kdY5c18+9KVcZPKinozprd1NsaOYfm3Sk2X1KFFWWGoMXTYynyUR757+fXHJ43Zct4unIXeDwxLMAB6n+gbsUxvKT+n3v+vq1YD1Ie0646yETlZMT8ubXCJbte3jg9UMXQQ+eXgS8kgvyuyYejsBl1ahltkGU0VxAlxmPTF3QNQ0xZrKE6EJ6eeoXD5JTgOzBEW+aaEPbYfQ4BfEHcWbGP3JukADOXj4ZsNlEpc8WMEJpijGxfOfweNbwANXzRmY+RlsfS889cHkgv+b//CcaeFlGMdPmn6AJRKp1afHaltRtYYp5nGX/RzIzosarbeV/OfVTVarNl/OhwGJbxVCD34knnnhEb11iFt3zDdSHRhHP575aS0J6S3mlDVVLKKPUKqQlxbZUs2C4y9gwGAvGJD0QmDaa/uNe+WaD0etFmcbLINyx5t2JgxpRcwVHDuhkbUUFY+bYZFFyuY5oahBNSnkMwnVDcMe1DsZKTzvYbZeajz1u75tYvqyFOPmlFYHNbjOyFAFVsx/RXgbgNyN4edVqa7TrFBGqbJSKNq/AXrcCpIAfe49oS1SkdvxlPqjsT2nOLLSY=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .
after_success:
- npm run coverage
