language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
  - "$(npm root -g)"

branches:
  only:
  - master
  - stage
  - test
  - dev
  - unit-testing

env:
  global:
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: "O6sVn6G1JHMEMVuT7VTGRf8XqxssyBKkRdgc72yI1D1xa+SksGWkYSJOzY03SEJTWhVozCJ/QCZ+K4FrBcwGDIF9P3kUVW5I6yMSezIcpuXizhRbqnqcyQtf/LnugOXIHkqePYla9czSTbcOmbq9oJNGvYPeg3B7B8IzYlFaIZRTtOvrWTVBRXnZ7TYIXW0sET+d5QHu/xoaPJVouMdVwxExrqtnIrfLd/AUyLb995ArND0fE513+jr/8nQXmy+TKQWUewzLS8viZv8rEJ3xUpnmeEM/DpFdnkTGuVXMBkOrDHzsPXxxisf+O9CKwCmN/rLTA1eP0sGHVixcAbjB01HvnSm6Qj/mT6nQwWY941s6rr7WL3o/5w/o24Uc8j4MbkyNPcQvAkJ36l3nIfDGjf7OZTNVaaEf0sa6c02oO66Dk17zZeGd37mAlXCokskanj7rki3Ae2m/li67JLYmVuiNa0uy1QUjEu0wBwlXDemJgAyhSNdQE7YmB+E8F8NIr0v869/UeCpgeq1fTXLfkwxgWJ+3oRvAW2KI7EUGBJboxljp3SRjtbpT0zGyofRt77Qsm8u3Cw9jUz3fBuPj14BzFrK5tVJFziPQkiYRF8HcgZcYW8NsjB0iDAGZ4Nruccc/WTKnJwwATZybU6i4WaJg6t61mAOO8mg3/0H59rQ="
  #COVERALLS_REPO_TOKEN=[secured]
  - secure: "REYJZVXH/vMZ+uq3zH6kLmrGuTLi7im7XX5fQhFFRKHPQ+cMMSD5Tik8bHi9wpusUWPS2ypvvEqig2b6AA/+GeblB0jphscBVjQSKB9tj4A9+GlNvXO6GetpJdZ1j9ELMmH5roLyS9uvKOEX91hXjva5f4KX4HxvWRth8DutxlRnfl+DNqkFNqiI79ZiJoyOKoJHUlkama4Rt5hBPMvKl2oYnl4g/Fp0Sa5s57nU9o9mUXdsoZFjPBmTsGOlpVldW4RCEmG8loq4CUqmB84Y14vIXG3sdOpQE/J3RBLPKSIO4j4ViSKmlVUgvFK7Rhr8t0CXJDcCo15Rvvwe5bh598seEOdIixYZdRarz0+6n2/nOrHxBRPVzAcBdpiBcboBnreNF/ChHPjDjN7LswlrSTRw/UZIN5Z7XnFoGAT8BMZSBB2jOBhv3yY4ieOFnQ/4AMcJBFIbJstoY0N039lI0sEliKgGvl6aFj7U0Dn2f4VosZvI7PsB08joHPGU9uKZZHoyYlGCds6UrqewhsiXZXv1+E03KfenGwA9+L7AMbaih9qdwrsGaRgKA6s8SEv8eEZk0Qhywgel3elN3ffdR/25+g1OJ7CSEkULaa08wUS9CU/LpzqSaYPI2T3EEm0DixqXAaooD5oWX7SNDCFs7F+ivEDR1sTzCxC+1dSgwms="
  #COVERALLS_SERVICE_NAME=[secured]
  - secure: "MN3FnnHd/I2Or69uyq21j4bL6Ix9uV2mECNQKXBdImtatvImCRAvl7IyOwCBeF5YkxQUS7Hf+09haatbMrbglZMUNFeTB/PJVZ44vm/vwK6gMm6QWujb0LNMt78gAunxEQb4yCS0leXleqVOPHy3Ja1mXZfD3oqRIHE1TI4BduBBKMQvaEbz7XYLwe/nrB3kBwVrBdnAK0wvwen2n/GrNIXXRp0S/UuKUdSLs3av/+MpvpWkaukX2MnaBb1e3Z46pjISVm5VpFpaIwvxTV8DbqQ0+47EUZnQRoOMx/9dGQjzrcUj+uC4ZeXUdA67hcEmTNuvuqrHScwWBSKENcnw1mDJWW7ntG1jjKZmH0jIe+Lcv1d3TOQrvIhZ+mZ9rlck3CPwJWKuzM9YeMFm5Zy7CG6wGFRIenUAVFpSJqy+bdDIE0GPycfZNE63xstzShFeRujpnKnzYlY4pC4ikoJHxppH+NuLisPQw1rIMtuB/b2uP9uC7I49r9WqwlXEPTVMDTruZ0huqVJzjrqlx/nkJAugbsRgyUYTi9hJfHNihxV2BqxHG/7+waIiUQtj3Wo7Ywlj0YG6GMIIXpOFjHyIJOr1Vb6OYvmjTEl+k3KeQbMfRSlTZ9Vf2V64/tjmZzFzoXs5nwMf+xemPf7UvdcGkje85Pqw1z15VlnGetiHeSc="
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: "EvQLp/rvid2riG4tAq3Q5o+vvKedYR9eKLX0WbFIVhUFsUclTKq4jw90ZFVQy7KsJ9D6896TLRotrgIlu9P2nXUz9PKf80+zut9sGgbJonmUahBQqL4KCDWjwIxRo7OpiOrqyyGGdCsmJR7bkIk6Ia9LUa9+L58srfHzDtsbJEe24Ijt6mDsdspA2vai3yQhV/dHsJCWg4Knis9lyl21Y/OMz3ZUvixeK2iJ50SYtGJhqj7Fzs/+6X5r0sR8XAHipxRpeZO2+7WBromeeX8X/xUf6Jaib+J175c9G8M2SC2d4exKSguTOenMgsMkNk1yLoolP4Xqxr0NPcJhHwCvOiDyP5QYcaPB5VyRAbNp1vt8NRPXpiazOxT2L51jEVLhBqPi255kXiScmAaZYQX0wZSMgPcsDifE2syF2hM0GzMsbEQLgDmuVN65x539Dh0BQYvqcRe6oF4znqg7IGeCDqCy21owrL1dJWEjvpRW82RJU7vhdZ3PXnl1HUbu8kdYTNpkbAkHATfC/KLFLzDWH1u4xj7ZTfK4NQFaSxkMi1+Y2xJhTp+y73wfFHl/045GrLmf6gunDLOvqt2BR6818j8rYtSt6qNBn855sebhd52PvNr1ZM/TjB7izqojhGDlUj2OWYcu4DM8NNUyekcvqENWZzHZC1OjuC0tP7/2Q1k="

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .

after_success:
- npm run coverage