language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - unit-testing
env:
  global:
    secure: NZOJKd3X4Ww+ULbf86iweo9e7Bna8d3FPWUn1jR3hVc7ChGuF57T5Dc3YJ7vfuutEGSo5cClGsoybxd7tfh5spvHrHzJ+9L8DAs0PpzaWd4aWl6X3Cj6FQgjTDotojsP5GMT6uPyBnwswqDOOwCqx3r8pahMZ/SfPhehSX5r4MZmhGs3mNSC21VV+AMJVLH9tQjuiQa/MJgVAkxY7UC0218QBguTuTS2foItixTB1xVVQFJ6vGDl/zV0egpq8p0zuxBd7aLMXQVw016PIHvh/JrLbncyvpZOclIbT89FMhaDq7Zo1qjhnTc+WE57TJRIEiBHP/cJo9F9Wjs/6cXP5FdBcrUO3mU93PKt60l55QTsRtaE/kGcUPLi5CBG+xj4Uvi+E9xY0Sc5Wjz+/PWnTwDxdlMCXlVSwEKRp26cl0+jnFIBx97bhIorHWLDxU/aE3rVmvvmm5Iz+q41dBpaJ6dB92BF2WPJKvDlC2PXuUmVYHmEC4yhxTiGmqzP/TyPBiiJbzL0lTJSxJzKntLUQj/6yiu5HOpVPDrG7fLBb4K3S/+KUBfXN94GYSOJ/Dxj34+tLKC/WkPRSr6yMOhrTl3s8vQDk1IEmuCvwEPnMBVfne+dn8qVS0kT8JFCgfa0/4qTrUcLJNVusln4uJEJIQrp57XOWUkCbcxgmtMXYQA=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g isparta
- npm install -g jasmine-core
- npm install -g karma
- npm install -g karma-jspm
- npm install -g karma-jasmine
- npm install -g karma-babel-preprocessor
- npm install -g karma-coverage
- npm install -g karma-verbose-reporter
- npm install -g phantomjs
- npm install -g karma-phantomjs-launcher
- npm install -g karma-chrome-launcher
- npm install -g karma-safari-launcher
- npm install -g karma-ng-html2js-preprocessor
- cp test/package.json .
after_success:
- npm run coverage
