exclude_paths:
  - '**/bin'
  - '**/test'
  - '**/tests'
  - '**/lib'
  - '**/tmp'
  - '**/vendor'
  - '**/.idea'
  - '**.spec.js'
  - '**.min.js'
  - '**.min.css'
  - '**/frontend/_build/'
  - '**/dist'
  - '**/node_modules'
  - '**/packages'
  - '**/font-awesome.css'
  - '**/materialdesignicons.css'
  - '**/DeepFramework.js'
  - '**/deep-framework.js'